const fs = require('fs-extra'),
    log = require('./log'),
    glob = require('glob'),
    os = require('os'),
    config = require('../../gulp-configuration'),
    upath = require('upath'),
    notifier = require('node-notifier'),
    rls = require('remove-leading-slash');

module.exports = {
    generate : function () {
        var success = true;
        var gitIgnoreRules = '';
        var source = upath.join('./', 'gulp-includes', '.gitignore');
        if (config.generateHtml.enable) {
            gitIgnoreRules += rls(upath.join(rls(config.generateHtml.output), '*.html')) + os.EOL;
            gitIgnoreRules += rls(upath.join(rls(config.generateHtml.output), 'gulp-documentation', '**', '*.html')) + os.EOL;
        }
        if (config.generateCss.enable) {
            var css_Files = '';
            var cssFiles = glob.sync(rls(upath.join(rls(config.generateCss.src_path), '*.scss')));
            cssFiles.forEach(function (file) {
                var filename = upath.basename(file).replace('.scss', '');
                css_Files += rls(upath.join(rls(config.generateCss.output_path), filename + '.css')) + os.EOL +
                    rls(upath.join(rls(config.generateCss.output_path), filename + '.css.map')) + os.EOL;
            });
            gitIgnoreRules += css_Files;
        }
        if (config.generateJs.enable) {
            var jsFiles = glob.sync(rls(upath.join(rls(config.generateJs.src_path), '*.js')));
            jsFiles.forEach(function (file) {
                var filename = upath.basename(file);
                delete require.cache[require.resolve('../../js/' + filename)];
                var fileConfig = require('../../js/' + filename);
                fileConfig = JSON.parse(JSON.stringify(fileConfig));
                gitIgnoreRules += rls(upath.join(rls(fileConfig.output_path), filename + '.map')) + os.EOL +
                    rls(upath.join(rls(fileConfig.output_path), filename)) + os.EOL;
            });
        }
        if (fs.pathExistsSync(source)) {
            var fileContent = fs.readFileSync(source, 'utf8');
            var finalContent = '### /!\\ Do not edit this file. See : gulp-includes/.gitignore /!\\ ###' + os.EOL +
                '### Rules generated by `gulp gitignore` ###' + os.EOL +
                gitIgnoreRules +
                rls(config.generateFavicon.output) + os.EOL +
                '### Rules from gulp-includes/.gitignore ###' + os.EOL + fileContent + os.EOL +
                '### /!\\ Do not edit this file. See : gulp-includes/.gitignore /!\\ ###';
            try {
                fs.outputFileSync('./.gitignore', finalContent);
            } catch (err) {
                success = false;
                notifier.notify({
                    title : 'Possible permission Error',
                    message : 'Cannot update or create file. Please check permissions.',
                    icon : './gulp-includes/core/images/fidesio-logo.png'
                });
                console.log(os.EOL);
                log.error(err);
                console.log(os.EOL);
            }
        } else {
            success = false;
            notifier.notify({
                title : 'Gitignore compilation Error',
                message : 'A file is missing.',
                icon : './gulp-includes/core/images/fidesio-logo.png'
            });
            console.log(os.EOL);
            log.error('ERROR! File ' + source + ' does not exist.');
            console.log(os.EOL);
        }
        return success;
    }
};